//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFilters
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLogger
    {
        public int Id { get; set; }
        public string ExceptionMessage { get; set; }
        public string ExceptionStackTrack { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ExceptionLogTime { get; set; }
    }
}
